---
title: "Visual model RMD"
author: "Joon Bum Yang"
date: "04/02/2022"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
```


## Load Data
```{r}
incidents<- read_csv('INCIDENTS.csv')
```

## Average Completion Time by status.
```{r}
ioh_avgtimestatus<- read_csv('IOH_avgTimeStatus.csv')

ioh_avgtimestatus%>%
  ggplot(aes(x=STATUS, y= TIME_IN_STATUS_BY_OWNER_HRS)) + geom_col()+ guides(x = guide_axis(n.dodge = 4), y.sec = guide_axis())

ioh_avgtimestatus
```

## Average Completion Time by Priority 
```{r}
inc_avgcmplserv_pr_stat<- read_csv('Inc_avgCmplServ_pr_stat.csv')

inc_avgcmplserv_pr_stat<-inc_avgcmplserv_pr_stat%>%
  group_by(PRIORITY)%>%
  summarize(avg_actual = mean(ACTUAL_COMPLETION_HRS, na.rm =T), avg_business =  mean(BUSINESS_COMPLETION_HRS, na.rm =T))


df_34 <- inc_avgcmplserv_pr_stat %>%
  gather("avg_business", "avg_actual", -PRIORITY)

ggplot(df_34, aes(x = PRIORITY, y = avg_actual, fill = avg_business)) +
  geom_col(position = "dodge")+ ggtitle("Average Completion Time by Priority") + ylab("Average Time Completed") + theme_minimal()
```

## Average Actual Completion Time by Services 95% percentile. 
```{r}
inc_avgcmplserv<- read_csv('Inc_avgCmplServ.csv')

inc_avgcmplserv2<-inc_avgcmplserv%>%
  filter(ACTUAL_COMPLETION_HRS < 10000)%>%
  filter(ACTUAL_COMPLETION_HRS > 1200)

inc_avgcmplserv2


line_avg = mean(inc_avgcmplserv$ACTUAL_COMPLETION_HRS, na.rm = T )

inc_avgcmplserv2%>%
  ggplot() + geom_col(aes(x = service, y = ACTUAL_COMPLETION_HRS), fill="steelblue") + ylab('Average Actaul Completion Time
') +  guides(x = guide_axis(n.dodge = 4), y.sec = guide_axis()) + xlab('Services')+ geom_hline(yintercept = line_avg, color = 'red')+ ggtitle("Top 5 Service with highest completion time") + theme_minimal() 



#+ geom_text(aes( 1, line_avg, label ='Average', vjust = -1), size = 3, color = 'red')

```

## Average Actual Completion Time by Organization
```{r}
inc_avgbizorg <- read_csv("Inc_avgBizORG.csv")

df_2<-inc_avgbizorg%>%
  filter(ACTUAL_COMPLETION_HRS > quantile(ACTUAL_COMPLETION_HRS,0.90, na.rm = T))

df_2

line_avg_2 = mean(inc_avgbizorg$ACTUAL_COMPLETION_HRS, na.rm = T )

df_2%>%
  ggplot() + geom_col(aes(x = org_id, y = ACTUAL_COMPLETION_HRS), fill="steelblue") + ylab('Average Actaul Completion Time
') +  guides(x = guide_axis(n.dodge = 1), y.sec = guide_axis()) + xlab('Organization ID')+ geom_hline(yintercept = line_avg_2, color = 'red')+ ggtitle("Top 7 Assigned Group with highest completion time") + theme_minimal() 




```


##Top 8 Assigned Group with highest estimated coefficient
```{r}
tisboh <- read_csv("TISBOH_AG_STAT.csv")
 
colnames(tisboh)[6] <- "P_value" 
colnames(tisboh)[5] <- "T_value" 


tisboh <-tisboh%>%
  mutate(index = substr(index, start = 15, stop = 22))


df_3 <- tisboh%>%
  filter(P_value < 0.005)%>%
  filter(abs(T_value) > 2)%>%
  filter(abs(Estimate) > 6000)

line_avg3 = mean(tisboh$Estimate, na.rm = T)

df_3%>%
  ggplot() + geom_col(aes(x = index, y = Estimate), fill="steelblue") + ylab('estimated coefficient
') +  guides(x = guide_axis(n.dodge = 2), y.sec = guide_axis()) + xlab('Group ID')+ geom_hline(yintercept = line_avg3, color = 'red')+ ggtitle("Top 8 Assigned Group with highest estimated coefficient") + theme_minimal() + theme(axis.text = element_text(size = 5))        





```


##Top 8 Service with highest estimated coefficient(abs)
```{r}
tisboh_serv <- read_csv("TISBOH_serv.csv")

colnames(tisboh_serv)[6] <- "P_value" 
colnames(tisboh_serv)[5] <- "T_value" 


tisboh_serv <-tisboh_serv%>%
  mutate(index = substr(index, start = 8, stop = 100))%>%
  filter(abs(Estimate) < 10000 )


df_4 <- tisboh_serv%>%
  filter(P_value < 0.005)%>%
  filter(abs(T_value) > 2)%>%
  filter(abs(Estimate) > 450 )



line_avg4 = mean(tisboh_serv$Estimate, na.rm = T)
  
  
  
df_4%>%
  ggplot() + geom_col(aes(x = index, y = Estimate), fill="steelblue") + ylab('estimated coefficient
') +  guides(x = guide_axis(n.dodge = 4), y.sec = guide_axis()) + xlab('Service')+ geom_hline(yintercept = line_avg4, color = 'red')+ ggtitle("Top 8 Service with highest estimated coefficient(abs)") + theme_minimal() + theme(axis.text = element_text(size = 8))        



```



  

